spring:
  application:
    name: DemoHttpSession

  data:
    redis:
      host: localhost
      port: 6379

  session:
    store-type: redis
    data:
      redis:
        namespace: "rikkei:pharmacy:session"
        save-mode: always

server:
  port: 8087